---
title: "EDA"
output: html_document
date: '2022-07-15'
---

```{r setup, echo = FALSE, include = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages

```{r cars, echo = FALSE, include = FALSE, warning = FALSE, message = FALSE}

library(tidyverse)
library(nflfastR)
library(ggrepel)
library(readr)
library(ggpubr)
library(knitr)

```


# Load Data

``` {r loadData, echo = FALSE, include = FALSE, warning = FALSE, message = FALSE}

fgPlays <- read_csv("Data/fgPlays.csv")

```


# Score Differential and Kick Distance Scatter Plot

```{r scatterScoreDistance, echo = FALSE, warning = FALSE, message = FALSE}

scoreDistanceScatter <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  select(score_differential, kick_distance, success, prev_def_team_to) %>%
  ggplot(aes(x = score_differential, y = kick_distance, color = as.factor(success))) + 
  geom_point(alpha = .5, size = .75) +
  facet_wrap(~prev_def_team_to) + 
  labs(x = "Score differential",
       y = "Kick distance") + 
  theme(legend.title = "Defensive TO or not") + 
  theme_minimal()
scoreDistanceScatter

```

# What proportion of field goals are taken immediately after a defensive timeout

```{r prop, echo = FALSE, warning = FALSE, message = FALSE}

prop <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  select(field_goal_attempt, prev_def_team_to) %>%
  group_by(field_goal_attempt, prev_def_team_to) %>%
  summarise(prop = mean(prev_def_team_to))
prop

count <- fgPlays %>%
  filter(field_goal_attempt == 1 & !is.na(prev_def_team_to)) %>%
  group_by(prev_def_team_to) %>%
  summarise(count = n())
count

propFG <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  group_by(prev_def_team_to) %>%
  summarise(prop = mean(success)) 
propFG

barProp <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>% 
  group_by(prev_def_team_to, field_goal_result) %>%
  summarise(count = n(),
            field_goal_result, prev_def_team_to,
            .groups = "drop") %>%
  ungroup() %>%
  group_by(prev_def_team_to) %>%
  summarise(total = n(),
            field_goal_result, prev_def_team_to, count,
            .groups = "drop") %>%
  mutate(prop = count / total) %>%
  ggplot(aes(x = as.factor(prev_def_team_to), 
             fill = field_goal_result)) +
  geom_bar(aes(y = prop), stat = "identity",
           position = "dodge") + 
  theme_minimal() + 
  theme(legend.position = "bottom")
barProp

```


# Density, etc. Plots

``` {r density, echo = FALSE, warning = FALSE, message = FALSE}

distanceDensity <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  ggplot(aes(x = kick_distance, color = as.factor(prev_def_team_to))) + 
  geom_density() + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(title = "Kick Distance",
       color = "Timeout")
distanceDensity

halfTimeDensity <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  ggplot(aes(x = half_seconds_remaining, color = as.factor(prev_def_team_to))) + 
  geom_density() + 
  scale_x_reverse() +
  geom_vline(xintercept = 900) + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(title = "Time Left in Half",
       color = "Timeout")
halfTimeDensity

gameTimeDensity <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  ggplot(aes(x = game_seconds_remaining, color = as.factor(prev_def_team_to))) + 
  geom_density() + 
  scale_x_reverse() +
  geom_vline(xintercept = 1800) + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(title = "Time Left in Game",
       color = "Timeout")
gameTimeDensity
  
winDensity <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  ggplot(aes(x = wp, color = as.factor(prev_def_team_to))) + 
  geom_density() + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(title = "Win Probability",
       color = "Timeout")
winDensity

epDensity <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  ggplot(aes(x = ep, color = as.factor(prev_def_team_to))) + 
  geom_density() + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(title = "Expected Points",
       color = "Timeout")
epDensity

scoreDensity <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  ggplot(aes(x = score_differential, color = as.factor(prev_def_team_to))) + 
  geom_density() + 
  geom_vline(xintercept = -3) +
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(title = "Score Differential",
       color = "Timeout")
scoreDensity


density <- ggarrange(distanceDensity, halfTimeDensity, gameTimeDensity, 
                    winDensity, epDensity, scoreDensity)
density

```


# Looking at some gambling data

```{r gambling, echo = FALSE, warning = FALSE, message = FALSE}

gamblingDensity <- fgPlays %>%
  filter(field_goal_attempt == 1, !is.na(prev_def_team_to)) %>%
  ggplot(aes(x = vegas_wp, color = as.factor(prev_def_team_to))) + 
  geom_density() + 
  theme_bw() +
  theme(legend.position = "bottom") + 
  labs(title = "Vegas Win Probability",
       color = "Timeout") 
gamblingDensity

```

# Create Nice Table of Variables and Descriptions

```{r variableDescriptions, echo = FALSE}

variableNames <- colnames(fgPlays)
variableNamesList <- data.frame(variableNames)

variableDesc <- c("Numeric play id that when used with game_id and drive provides the unique identifier for a single play", 
                  "Ten digit identifier for NFL game", 
                  "Legacy NFL game ID", 
                  "String abbreviation for the home team", 
                  "String abbreviation for the away team", 
                  "String indicating the type of play: pass (includes sacks), run (includes scrambles), punt, field_goal, kickoff, extra_point, qb_kneel, qb_spike, no_play (timeouts and penalties), and missing for rows indicating end of play", 
                  "Binary indicator for whether or not a timeout was called by either team", 
                  "String abbreviation for the team with possession", 
                  "String abbreviation for the team on defense", 
                  "Prev_def_team_to", 
                  "is_iced_kick", 
                  "Detailed string description for the given play", 
                  "Numeric seconds remaining in the half", 
                  "Numeric seconds remaining in the game", 
                  "Binary indicator for whether or not the row of the data is marking the end of a quarter", 
                  "Binary indicator for whether or not a score occurred on the play", 
                  "Quarter of the game (5 is overtime)", 
                  "Binary indicator for whether or not the posteam is in a goal down situation", 
                  "String indicating the current field position for a given play", 
                  "Numeric distance in the number of yards from the opponent's endzone for the posteam", 
                  "Numeric yards in distance from either the first down marker or the endzone in goal down situations", 
                  "String indicator for result of field goal attempt: made, missed, or blocked", 
                  "Numeric distance in yards for kickoffs, field goals, and punts", 
                  "Score differential between the posteam and defteam at the start of the play", 
                  "Score differential between the posteam and defteam at the end of the play", 
                  "Binary indicator for field goal attempt", 
                  "String name for the kicker on FG or kickoff", 
                  "Unique identifier for the kicker on FG or kickoff", 
                  "Game time at the end of a given play", 
                  "Equals home_score - away_score and means the game outcome from the perspective of the home team",
                  "Binary indicator wheter epa > 0 in the given play", 
                  "Binary indicator if the play was a special teams play", 
                  "String indicating which half the play is in, either Half1, Half2, or Overtime", 
                  "Estimated win probabiity for the posteam given the current situation at the start of the given play", 
                  "Using the scoring event probabilities, the estimated expected points with respect to the possession team for the given play", 
                  "Estimated win probabiity for the posteam given the current situation at the start of the given play, incorporating pre-game Vegas line")

variableDescList <- data.frame(variableDesc)

variablesTable <- cbind(variableNamesList, variableDescList)
colnames(variablesTable)[1] <- "Variable Names"
colnames(variablesTable)[2] <- "Description"
kable(variablesTable)

```








